# Generated by Django 4.1.1 on 2022-09-08 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipAdress', models.GenericIPAddressField()),
                ('text', models.TextField()),
                ('date', models.DateTimeField()),
                ('reportCount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Nakdong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wtqltObsrvtCd', models.TextField()),
                ('obsrvtNm', models.TextField()),
                ('msmtTm', models.DateTimeField()),
                ('altdDpwt', models.TextField()),
                ('mesureDpwt', models.TextField()),
                ('wtep', models.TextField()),
                ('saln', models.TextField()),
            ],
        ),
    ]
