# Generated by Django 4.1.1 on 2022-09-10 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nakdong', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nakdong',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
